name: deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/setup-java@v2
            with:
              java-version: '11'
              distribution: 'adopt'
          - run: wget https://www-eu.apache.org/dist/ambari/ambari-2.7.7/apache-ambari-2.7.7-src.tar.gz
          - run: tar xfvz apache-ambari-2.7.7-src.tar.gz
          - run: |
              cd apache-ambari-2.7.7-src && \
              mvn versions:set -DnewVersion=2.7.5.0.0
          - run: |
              cd apache-ambari-2.7.7-src/ambari-metrics && \
              mvn versions:set -DnewVersion=2.7.7.0.0
          - run: |
              cd apache-ambari-2.7.7-src && \
              mvn -B clean install jdeb:jdeb -DnewVersion=2.7.7.0.0 -DbuildNumber=388e072381e71c7755673b7743531c03a4d61be8 -DskipTests -Dpython.ver="python >= 2.6"
          - uses: actions/upload-artifact@v2
            with:
              name: ambari-server
              path: ./ambari-server*.deb
          - uses: actions/upload-artifact@v2
            with:
              name: ambari-agent
              path: ./ambari-agent*.deb
